export default {
    productCreated: 'productCreated',
    productDeleted: 'productDeleted',
    productUpdated: 'productUpdated',
    productAttributeCreated: 'productAttributeCreated',
    productAttributeDeleted: 'productAttributeDeleted',
    productAttributeUpdated: 'productAttributeUpdated',
    productCategoryCreated: 'productCategoryCreated',
    productCategoryDeleted: 'productCategoryDeleted',
    productCategoryUpdated: 'productCategoryUpdated',
    productCategoryAttributeCreated: 'productCategoryAttributeCreated',
    productCategoryAttributeDeleted: 'productCategoryAttributeDeleted',
    productCategoryAttributeUpdated: 'productCategoryAttributeUpdated',
    productSkuCreated: 'productSkuCreated',
    productSkuDeleted: 'productSkuDeleted',
    productSkuUpdated: 'productSkuUpdated',
}